import React, { useState } from "react";
import { TouchableOpacity, Text, StyleSheet, ActivityIndicator } from "react-native";
import { Icon } from "react-native-elements";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { useTheme } from "../../../app/providers/ThemeContext";
import ShowErrorNotification from "../../../components/ui/ShowErrorNotification";

/**
 * ExportQuizButton component allows users to generate a PDF version of the quiz
 * and share it using the device's native sharing capabilities.
 * 
 * @param {Object} quiz - The quiz object containing name, description, and questions.
 */
export default function ExportQuizButton({ quiz }) {
    const { theme } = useTheme();
    const [exporting, setExporting] = useState(false);

    const generateHtml = () => {
        const questionsHtml = quiz.questions?.map((q, index) => `
      <div class="question-block">
        <p class="question-text"><b>Question ${index + 1}:</b> ${q.content}</p>
        <ul class="options-list">
          ${q.options?.map(opt => `
            <li class="option-item ${opt.is_correct ? 'correct' : ''}">
              [ ] ${opt.content} ${opt.is_correct ? ' (Correct Answer)' : ''}
            </li>
          `).join('')}
        </ul>
      </div>
    `).join('') || '<p>No questions available.</p>';

        return `
      <html>
        <head>
          <style>
            body { font-family: 'Helvetica', sans-serif; padding: 20px; color: #333; }
            .header { border-bottom: 2px solid ${theme.colors.primary}; padding-bottom: 10px; margin-bottom: 20px; }
            .title { font-size: 24px; font-weight: bold; color: ${theme.colors.primary}; }
            .description { font-size: 14px; color: #666; margin-top: 5px; }
            .question-block { margin-bottom: 20px; page-break-inside: avoid; }
            .question-text { font-size: 16px; margin-bottom: 10px; }
            .options-list { list-style-type: none; padding-left: 10px; }
            .option-item { margin-bottom: 5px; font-size: 14px; }
            .correct { color: #27AE60; font-weight: bold; }
            .footer { margin-top: 50px; font-size: 10px; text-align: center; color: #999; }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="title">${quiz.name || 'Untitled Quiz'}</div>
            <div class="description">${quiz.description || 'No description provided.'}</div>
          </div>
          ${questionsHtml}
          <div class="footer">Generated by AI Quiz Platform</div>
        </body>
      </html>
    `;
    };

    const handleExport = async () => {
        if (!quiz) return;
        setExporting(true);
        try {
            const html = generateHtml();
            const { uri } = await Print.printToFileAsync({ html });

            if (await Sharing.isAvailableAsync()) {
                await Sharing.shareAsync(uri, {
                    mimeType: 'application/pdf',
                    dialogTitle: `Share Quiz: ${quiz.name}`,
                    UTI: 'com.adobe.pdf',
                });
            } else {
                alert("Sharing is not available on this device");
            }
        } catch (error) {
            ShowErrorNotification({ message: "Failed to export PDF", cause: error });
        } finally {
            setExporting(false);
        }
    };

    return (
        <TouchableOpacity
            style={[
                styles.button,
                { backgroundColor: theme.dark ? "rgba(255,255,255,0.1)" : "#f0f0f0" }
            ]}
            onPress={handleExport}
            disabled={exporting}
        >
            {exporting ? (
                <ActivityIndicator size="small" color={theme.colors.primary} />
            ) : (
                <>
                    <Icon name="picture-as-pdf" type="material" size={20} color={theme.colors.primary} />
                    <Text style={[styles.text, { color: theme.colors.primary }]}>Export PDF</Text>
                </>
            )}
        </TouchableOpacity>
    );
}

const styles = StyleSheet.create({
    button: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 8,
        gap: 6,
        alignSelf: 'flex-start',
    },
    text: {
        fontSize: 14,
        fontWeight: "600",
    },
});
